name: amolie

services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: amolie
    ports:
      - '5432:5432'
    volumes:
      - amolie_postgres:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - amolie_redis:/data

volumes:
  amolie_postgres:
  amolie_redis:
