// Root ESLint config, used directly by packages/* that don't need
// framework-specific rules (apps/web and apps/api ship their own
// eslint.config.mjs generated by their respective official CLIs).
import js from '@eslint/js';
import eslintConfigPrettier from 'eslint-config-prettier';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: ['**/dist/**', '**/.next/**', '**/node_modules/**', '**/coverage/**'],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  eslintConfigPrettier,
);
